# Generated by Django 4.1 on 2022-09-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unique_Number', models.CharField(max_length=100)),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Type', models.CharField(max_length=90)),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Stock', models.IntegerField()),
                ('Stock_Date', models.DateField()),
            ],
        ),
    ]
